### ISSUE TITLE
Issue - mapping not working

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#10]
Hi Mathielen,

I'm digging in full-force in the ImportEngine, so sorry for the questions.

I have started from your config example with a mapping, but the mapping seems to be ignored.

```
# Importer configuration
mathielen_import_engine:
    #configure storageproviders, that are used in all importers
    storageprovider:
        default:
            type: directory
            uri: '%kernel.root_dir%/../web/imports/parcel'
        upload:
            type: upload
            uri: "%kernel.root_dir%/../web/imports/upload"

    #configure your Importers
    importers:
        importer_bol:
            #some context information that is passed through the whole process
            context:
                key: bol

            #automaticly recognize this importer by meeting of the conditions below
            preconditions:
                format: excel               #format of data must be [csv, excel, xml]
                fieldcount: 2               #must have this number of fields
                fields:                     #these fields must exist (order is irrelevant)
                    - 'header2'
                    - 'header1'
                fieldset:                   #all fields must exist exactly this order
                    - 'header1'
                    - 'header2'
#                filename: 'somefile.xls'    #filename must match one of these regular expression(s) (can be a list)

            #add mapping
            mappings:
                #simple a-to-b mapping
                source-field1: target-field2

                #map and convert
                source-field2:
                    to: target-field1
                    converter: upperCase    #use a converter that was registered with the converter-provider

            #target of import
            target:
                type: service               #[service, doctrine, file]
                service: 'parcel_service'   #service name in DIC, !!remark no @ needed
                method: processImportRow    #method to invoke on service 
```

My service method 'processImportRow' currently only dumps the target data.

In my mapping example I try to switch the order to a different field, but they remained the same.

> Commencing import using importer importer_bol with source provider default and source id /Users/tim/Desktop/testTim.csv
>  0/2 [>---------------------------]   0%array:2 [
>   "header1" => "Line 1 A"
>   "header2" => "Line 1 B"
> ]
>  1/2 [==============>-------------]  50%array:2 [
>   "header1" => "Line 2 A"
>   "header2" => "Line 2 B"
> ]
>  2/2 [============================] 100%
> Import done
> 
> +------------+---+
> | Statistics |   |
> +------------+---+
> | processed  | 2 |
> | written    | 2 |
> | skipped    | 0 |
> | invalid    | 0 |
> +------------+---+
>

**Comment by thim81** [comment]
I expected to see somehting like this:

"header1" => "Line 1 B"
"header2" => "Line 1 A"

**Comment by mathielen** [comment]
Please try to UPPERCASE the sourcefield...

```
SOURCE-FIELD2:
    to: target-field1
    converter: upperCase
```   

I guess thats the problem. Another thing to clear in the docs or to fix :)

**Comment by thim81** [comment]
Regarding the "SOURCE-FIELD1" is this a name reference used by the engine or should I use the real data "header1"

```
 #add mapping
            mappings:
                #map and convert
                SOURCE-FIELD1:
                    to: target-field1
                    converter: upperCase    #use a converter that was registered with the converter-provider
```

or

```
 #add mapping
            mappings:
                #map and convert
                "header1":
                    to: target-field
                    converter: upperCase    #use a converter that was registered with the converter-provider
```

**Comment by thim81** [comment]
Because I tried:
```
 #add mapping
            mappings:
                #map and convert
                SOURCE-FIELD1:
                    to: target-field1
                    converter: upperCase    #use a converter that was registered with the converter-provider
```

But it didn't switched the data?
