### ISSUE TITLE
Question - process all files in storageprovider

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#19]
Hi Markus,

Me again, Is it possible for the importEngine to process all files in certain storageprovider?

```
mathielen_import_engine:
    #configure storageproviders, that are used in all importers
    storageprovider:
        default:
            type: directory
            uri: '%kernel.root_dir%/../web/imports/parcel'
        upload:
            type: upload
            uri: "%kernel.root_dir%/../web/imports/upload"
```

Example: I want to process all files in the "upload" storage provider?

> importengine:import [-i|--importer="..."] [-c|--context="..."] [-l|--limit="..."] [-d|--dryrun] source_id [source_provider]

if I try it with 

`app/console importengine:import -i importer_bol --env=dev default`

I get the following error:
```
[InvalidArgumentException]
  id is not a valid file path: default
```

The importengine:import requires the "source_id" but what do you mean with this?
