### ISSUE TITLE
Setting csv arguments ',' in importer without 'source'

### ISSUE THREAD

**Issue by Notmarrco** [mathielen/ImportEngineBundle#21]
Hi,

I have a csv with ',' separators instead of ';'. 
In my importer I thought I could use : 
```yaml
preconditions:
    format: { type: csv, arguments: [','] }
```
but it's not possible. 

I saw in the Configuration dependencyInjection that the arguments are available only in ```source``` or ```target``` options. Then when I try with ```source```, the separator is well set, but the ```source: uri``` is mandatory.
So I'm left with : 
- either I can choose my file in command line, but I can't use ',' separator
- or I have to always use the same name, defined in the ```source``` options

Am I missing something ?

Thx

**Comment by thim81** [comment]
Hi Notmarrco,

Could you share your full configuration?

The preconditions part should be a valid format

```
 preconditions:
                format: csv               #format of data must be csv OR excel OR xml
                fieldcount: 2               #must have this number of fields
....
```

With regards to the CSV "," vs ";" I think the CSV format handler detects the seperator itself, so it is not necessary to define it, but I'm not 100% since in my use-cases I have always used Excel documents.

**Comment by Notmarrco** [comment]
Hi

Here is my configuration : 
```yml
    importers:
        generic_importer:
            #some context information that is passed through the whole process
            context:
                key: generic_importer
            #automaticly recognize this importer by meeting of the conditions below
            preconditions:
                format: csv
                fieldcount: 3 
                fields:
                    - 'fullname'
                    - 'login'
                    - 'email'
                filename: 'Export_generic.csv'
          
            source: 
                type: file
                uri: web/uploads/tmp/Export_generic.csv
                format: { type: csv, arguments: [','] }                         
                
            #target of import
            target:
                type: service
                service: 'generic.user.crud' 
                method: processImportRow  
```

Here the problem is that my csv file is separated with ',' and not with semicolons. So without the *source* part of my configuration (this one : ) 
```yml
            source: 
                type: file
                uri: web/uploads/tmp/Export_generic.csv
                format: { type: csv, arguments: [','] }           
```

when I try to import a file, it does find only one big field with "fullname,login,email" as header, instead of my 3 fields.

The only way I found was to use the "source" part, but : 
- I can't modify the name of the file I want to import in cli
- and this source configuration takes precedence over *preconfigurations* parameters.

What I want is to make rid of "source" configuration part and to be able to say to the importer that the separator is ','.

**Comment by thim81** [comment]
Hi Notmarco,

I haven't run into this issue, but I assume indeed that this is linked to the deboer bundle and how it's implemented.

Perhaps Markus know how to solve this.

**Comment by Notmarrco** [comment]
Hi, thanks for your answer. I will wait for @mathielen then.

I also think it can be related to the ImportEngine, and the auto csv class : it seems that it find a "space" in the file and use it as a separator when guessing what is the separator.

In fact it shouldn't have to "guess" the separator, since I gave him the fields (and I also tried with a fieldset) I'm waiting for..

**Comment by mathielen** [comment]
Hi Notmarco,

Ok so, its perfectly correct to do 
```yaml
            source: 
                type: file
                uri: web/uploads/tmp/Export_generic.csv
                format: { type: csv, arguments: [','] }      
```
And it works - for exactly one specific file. You are right, you cannot invoke the importer from the CLI then. The importer would be very "static".

This is what the *StorageProvider classes are for. So by default there is a FileStorageProvider which uses a FormatDiscoverLocalFileStorageFactory to automatically find the format of the file, which in your case does not need to be discovered.
So what you could do is, register a different source_provider and tell the engine to use it instead. (Its the second argument of the CLI command). You could use a ServiceStorageProvider (type=service) and handle your logic there.
And yes, I know its not very elegant. I will put this on my roadmap :)

Best
Markus
