### ISSUE TITLE
Question - documentation example 

### ISSUE THREAD

**Issue by thim81** [mathielen/ImportEngineBundle#23]
Hi Markus,

Another question: As I understood the "target" is where the data is send to?
So in your minimum example:

```
another_minimum_importer:
            target:
                type: file
                uri: "@='%kernel.root_dir%/../output_'~date('Y-m-d')~'.csv'"    #this uses symfony expression language
                                                                                #to create the filename. Just prefix your
                                                                                #expression with @=
                format: { type: csv, arguments: [','] }                         #delimiter is now ','   
```

This would be the config to "export" data to a CSV file base on the target?
Or is this a config option to for an importer?

Regards,
Tim
