### ISSUE TITLE
Problem using the doctrine storage provider 

### ISSUE THREAD

**Issue by sfahrenkrog** [mathielen/ImportEngineBundle#3]
Using the following configuration: 

```
mathielen_import_engine:
    #configure storageproviders, that are used in all importers
    storageprovider:
        doctrine:
            type: doctrine
            queries:
                    - Bankinero\DatevBundle\Entity\ShopOrder     
    importers:      
        datev:
            target:
                type: file
                uri: "%kernel.root_dir%/export/datev.csv"
                format: csv 
```

Starting import with: 
```
app/console importengine:import -i datev 0 doctrine
```
Results in 

```
Commencing import using importer datev with source provider doctrine and source id 0

  [Doctrine\ORM\Query\QueryException]                                                            
  [Semantical Error] line 0, col 21 near 'SELECT o FROM': Error: Class 'SELECT' is not defined.  
                                                                                                                                                                                  
  [Doctrine\ORM\Query\QueryException]                                            
  SELECT count(o) FROM SELECT o FROM Bankinero\DatevBundle\Entity\ShopOrder o o  
                                                                                 
```
