### ISSUE TITLE
use as export

### ISSUE THREAD

**Issue by Avtonom** [mathielen/ImportEngineBundle#5]
```yml
mathielen_import_engine:
    storageprovider:
        default:
            type: doctrine
            queries:
                - AppBundle\Entity\Client
    importers:
        avantage_importer:
            object_factory:
                type: default
                class: AppBundle\Entity\Client
            target:
                type: service
                service: service_writer
                method: writeItem
```

```php
    public function writeItem(Client $client)
    {
        var_dump($client);
```

```
Bobject(AppBundle\Entity\Client)#587
(4) {
  ["id":protected]=>  NULL
  ["name":protected]=>   NULL
  ["id"]=>  string(0) "123"
  ["name"]=>  string(0) "Anton"  
```

if  use:
```php
    $client->getName()
```
view:
```
NULL
```

**Comment by Avtonom** [comment]
rewrite:
```yml
            object_factory:
#                type: default
#                class: AppBundle\Entity\Client
                type: jms_serializer
                class: AppBundle\Entity\Client
```
but jms_serializer not use 
```yml
        accessor:
          getter: getFuu
```
