### ISSUE TITLE
Argument 1 passed ValidatorInterface

### ISSUE THREAD

**Issue by Avtonom** [mathielen/ImportEngineBundle#6]
````yaml
            validation:
                source:
                    id: notempty
````

Catchable Fatal Error: Argument 1 passed to Mathielen\ImportEngine\Validation\ValidatorValidation::__construct() must be an instance of Symfony\Component\Validator\ValidatorInterface, instance of Symfony\Component\Validator\Validator\RecursiveValidator given, called
